### PR TITLE
Create mergesort.go

### PR DESCRIPTION
**Pull request by duffleit**
hey buffaloluk7, i added mergesort (untested)

### CODE REVIEW

**Comment by buffaloluk7** [comment]
Hello David,

nice try, but you need write some unit tests before we can accept your pull request.

**Comment by thomaseizinger** [comment]
Wrong repo.

**Comment by buffaloluk7** [comment]
Or should we just rename it?

**Comment by thomaseizinger** [comment]
I propose the following:
- Rename to sort
- Introducing parameters (-strategy merge | quick AND -parallel)

**Pull request closed without merging**
